### ISSUE TITLE
Please upgrade to the latest version to get a critical bugfix

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/mixin-deep#4]
## Heads up!

_**NPM should no longer be listing this as a vulnerability.**_

We worked with Snyk to resolve this immediately when it was reported, you can confirm that it was fixed by running `snyk` (instead of `npm audit`). See https://github.com/base/base/issues/36 for more details.

v2.0.1 is a patch release to prevent unsafe properties from being assigned. See [this guide](https://gist.github.com/jonschlinkert/9a62534c4f8bc76aee6058caa3f05fd6) if you need more assistance.

**Comment by STRML** [comment]
`1.3.2` also fixes this vulnerability, but is not recognized as fixing it by `yarn audit`.

**Comment by jonschlinkert** [comment]
https://github.com/micromatch/micromatch/issues/174
