### ISSUE TITLE
Use tag instead of branch for 1.3.2

### ISSUE THREAD

**Issue by tnir** [jonschlinkert/mixin-deep#5]
Can you use tag instead of branch for 1.3.2 to find the latest 1.x release on https://github.com/jonschlinkert/mixin-deep/releases?

I can now see 1.3.2 on branches:

- https://github.com/jonschlinkert/mixin-deep/branches

**Comment by tnir** [comment]
@jonschlinkert @doowb Thanks for patching the vulnerability for 1.x as well as 2.x!! 😃

**Comment by doowb** [comment]
I'll try getting it tagged.

**Comment by danepowell** [comment]
I was really thrown by this. In trying to track down the vulnerability errors, I saw that there was no 1.3.2 mixin-deep release on Github and this led me to believe that the vulnerability was valid.

I've only just seen that in fact 1.3.2 exists as a release on npm, but not Github. Maybe this is part of the reason why everyone / everything (vuln scanners) is confused.

Additionally, it would help a lot if this were mentioned in the docs page / pinned post / maintainer responses to this issue. Saying "just go away and run npm install again" isn't entirely constructive.

**Comment by doowb** [comment]
@tnir I renamed the branch and tagged the commit.

**Comment by tnir** [comment]
@doowb Confirmed as fixed. Thanks a lot 🚀
