### ISSUE TITLE
Your minor bump from 1.3.1 to 1.3.2 broke semver and needs to major bump

### ISSUE THREAD

**Issue by ahungry** [jonschlinkert/mixin-deep#7]
```javascript 
          it('should do a deep merge', function () {
             var obj1 = { a: { prototype: { a: 1 }, b: 1, c: 1, d: { e: 1, f: 1 } } };
             var obj2 = { a: { prototype: { b: 1 }, b: 2, d: { f: 'f' } } };

             mixinDeep(obj1, obj2).should.eql({ a: { prototype: { a: 1, b: 1 }, b: 2, c: 1, d: { e: 1, f: 'f' } } });
           });
```

Please see above - that test passes on 1.3.1, it fails on 1.3.2.  That means you have altered the input/output contract of this package, so I don't think a "bugfix" bump is warranted.

**Comment by ahungry** [comment]
```sh
  1 failing
                                                                                                                                                                                                                                             
  1) .mixinDeep() should do a deep merge:                                                                                                                                                                                                    

      AssertionError: expected Object {
  a: Object { prototype: Object { a: 1 }, b: 2, c: 1, d: Object { e: 1, f: 'f' } }
} to equal Object {
  a: Object {
    prototype: Object { a: 1, b: 1 },
    b: 2,
    c: 1,
    d: Object { e: 1, f: 'f' }
  }
} (at a -> prototype, A has Object { a: 1 } and B has Object { a: 1, b: 1 })
      + expected - actual

             "f": "f"
           }
           "prototype": {
             "a": 1
      +      "b": 1
           }
         }
       }
      
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (test.js:43:34)
```

**Comment by ahungry** [comment]
As you can see, what was previously a valid key and would merge the children candidates simply fails silently now and does not merge at all.

**Comment by doowb** [comment]
`prototype` is not a valid key to allow to be mixed in. If it was, it would allow a prototype pollution attack and is the reason why the older version of `mixin-deep` was patched.

**Comment by ahungry** [comment]
Where in the 1x branch is it stated to be invalid?  It clearly worked fine for object literals previously as shown by the test, and perhaps more effort should have went into this "fix" to just prevent/guard against an actual attack, by handling the cases where it could manifest, not cases where it's a non-issue.

In this file, it indicates there WAS a major version bump to fix this already (a properly semver'ed change, as this was a BC break and probably the reason the lib moved from 1x to 2x).

For you to "bugfix" bump a Bc breaking change (that already received the semver major bump) seems very wrong - your downstream users of this package should knowingly move forward to 2x, not be forced to have a change that could alter behavior in unexpected ways on 3 million apps that dependon this lib.

**Comment by ahungry** [comment]
https://github.com/jonschlinkert/mixin-deep/blob/master/.verb.md

**Comment by FlorianWendelborn** [comment]
@ahungry if this would’ve been a major bump, millions of people wouldn’t upgrade to it automatically and run insecure versions of `mixin-deep`. While this may have caused you some issues, I think it’s the right call since security is more important than DX.
